### PR TITLE
Put com.spotify imports 2nd instead of com.google

### PR DESCRIPTION
**Pull request by davidxia**
Put com.spotify imports first and static ones last.

### CODE REVIEW

**Comment by davidxia** [comment]
@pettermahlen @mattnworb @rohansingh

**Comment by mattnworb** [comment]
👍

**Comment by pettermahlen** [comment]
The relevant section in the google style guide is this: https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing. 

It's clearly stating 'static' should come first, followed by 'com.google', if the 'com.google' namespace is used. The second rule will never apply to our code. I understand this PR as suggesting that we should replace that second rule with the corresponding Spotify rule?

I'd be opposed to changing the position of 'static' imports, because it doesn't matter (I think) and therefore it's much better to just stick to the original guidelines. Regarding 'com.google'/'com.spotify', I think we have two choices: 
1. Drop 'com.google' as a group. This would mean we conform to the Google style guides, and would make the `spotify_checks.xml` file useful for style checking outside of Spotify.
2. Replace 'com.google' with 'com.spotify' in our rules. This will highlight imports of our own code more clearly.

I'm not completely sure, but I think I'm leaning towards option 1. I don't think import highlighting is very important - and neither is, probably, general applicability of our style guide. But option 1 would make it more suitable for things like personal projects, which is at least of some value.

@dflemstr @rouzwawi @mattnworb @mbruggmann @jo-ri any opinions?

**Comment by mbruggmann** [comment]
I'm with @pettermahlen on this one, would vote for dropping the `com.google` group and keeping static first.

**Comment by mattnworb** [comment]
I should take back my one-emoji comment from before. +1 to removing the special case for Google - no one needs that but them. 

I am ambivalent about the other parts. It's more valuable to me to have a convention on those than what the details of the convention are. The only thing I would suggest considering is whichever import order has the least friction with the majority of existing code.

**Comment by rouzwawi** [comment]
My 2c

I vote for option 2 and I'm leaning more towards having static imports last just because as Matt said, it's the option with least friction with existing code.

**Comment by davidxia** [comment]
Yea, my primary motivation was less friction with existing code. If existing code bases aren't likely to switch to this checkstyle, this is less of a concern. But I'd also consider what people's default IDE settings are. IntelliJ seems to default to static imports last.

It'd be nice to supply compatible IDE config files. We could base them on the ones here https://github.com/google/styleguide.

**Comment by pettermahlen** [comment]
I'm not sure the friction argument is super-important, in particular not if we also include an IDEA configuration that corresponds to the checkstyle config. That would make it trivial for people to update their source code gradually.

It's more important to me to minimise the amount of time we spend on discussing diverging from the code style, and I think a good way of doing that is via not diverging. :) #2 is arguably in keeping with the Google style guide (as the variable name in a `catch` clause is temporary), but reordering static imports is clearly not.

**Comment by mattnworb** [comment]
> It's more important to me to minimise the amount of time we spend on discussing diverging from the code style

agreed 💯

**Comment by davidxia** [comment]
Also agreed. I'll leave the static import order as is and replace com.google with com.spotify.

**Comment by mattnworb** [comment]
👍  after 904f20d

**Comment by davidxia** [comment]
@pettermahlen Can we merge this?

**Comment by pettermahlen** [comment]
👍 absolutely; and I don't feel I should be seen as having any kind of final say on that, so if there are other things you want to merge, go ahead.

**Pull request merged**
