### PR TITLE
Relax catch parameter name rules

### PR DESCRIPTION
**Pull request by davidxia**
So we can use `e`.

### CODE REVIEW

**Comment by davidxia** [comment]
@pettermahlen

**Comment by kouKatsumi** [comment]
Are we sure we want to have 'e' only? Isn't 'ex' more readable? 
If yes :+1:

**Comment by davidxia** [comment]
I don't have a strong opinion. I just got into the habit of only using `e`.

**Comment by pettermahlen** [comment]
This proposal seem to go against the Google code style: https://google.github.io/styleguide/javaguide.html#s5.2.7-local-variable-names. 

I personally like it, especially that it's only changing the catch parameter names, not local parameter names in general. The question for me is to what extent we're opening Pandora's box by changing the Google conventions. Adding some peeps with Java interests to collect more opinions:

@mbruggmann @mattnworb @rouzwawi @dflemstr @jo-ri

**Comment by mattnworb** [comment]
Requiring two chars seems reasonable to me but I don't have a strong feeling. 

(For what it's worth if you have a rule that says at least one char, I don't think you even need the rule for exception names then, as any variable has to start with an alphabet character and I assume leading upper-case chars are illegal from other checkstyle rules)

**Comment by rouzwawi** [comment]
No strong opinion: `catch (SomeException _____) { ... }` is always readable :)

**Comment by udoprog** [comment]
Guava frequently uses `e` (`git grep ' e)' | grep catch | wc -l => 842`), the style guide has several 'good' examples including it. I think the following provision from the style guide permits it:

```
5.2.7 Local variable names
[...]
However, one-character names should be avoided, except for temporary and looping variables.
```

This would seem like it qualifies as _temporary_.

**Comment by davidxia** [comment]
I have no strong opinion and would be fine with defaulting to google.

On Wednesday, June 29, 2016, John-John Tedro notifications@github.com
wrote:

> Guava frequently uses e (git grep ' e)' | grep catch | wc -l => 842), the
> style guide has several 'good' examples including it. I think the following
> provision from the style guide permits it:
> 
> 5.2.7 Local variable names
> [...]
> However, one-character names should be avoided, except for temporary and looping variables.
> 
> This would seem like it qualifies as _temporary_.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/spotify/spotify-checkstyle-config/pull/2#issuecomment-229352816,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAdVbUGxOVzGYwGrAqj8Z9GPgvrMEFx4ks5qQnCugaJpZM4I_WCo
> .

## 

David Xia
Software Engineer
dxia@spotify.com

**Comment by mattnworb** [comment]
As another data point - a quick search of our internal codesearch (assuming it is working correctly) only shows 2 hits for the phrase "CatchParameterName", suggesting that this is not really a checkstyle rule in wide use today and that existing code is probably using all sorts of variations.

(I originally posted "14 hits" but then I noticed 12 of these were in javascript files, and just two in files ending in `*.xml`.)

**Comment by davidxia** [comment]
Is friction with existing code a concern as it is here? https://github.com/spotify/spotify-checkstyle-config/pull/1#issuecomment-229329351 If people upgrade, it will be annoying to see warnings because they used `e` instead of `ex`. I did this to a project on warpspeed, got 50 warnings, and was tempted to remove checkstyle completely. I ended up increasing the checkstyle failure thresholds to 100. :)

**Comment by pettermahlen** [comment]
I'm going to go ahead and merge this; I think it's very common and unproblematic to use single-letter names for exceptions.

**Comment by davidxia** [comment]
Thanks, @pettermahlen.

**Pull request merged**
